services:
  api_gateway:
    image: ghcr.io/reels-automation/reels-automation-api-gateway-new:main
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      JWT_KEY: ${JWT_KEY}
      MINIO_URL: ${MINIO_PUBLIC_URL}
      MONGO_URL: ${MONGO_URL}
      KAFKA_URL: ${KAFKA_URL}
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_PUBLIC_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PUBLIC_SECRET_KEY}
      MINIO_PUBLIC_URL_SIGN_FILES: ${MINIO_PUBLIC_URL_SIGN_FILES}
    container_name: api_gateway
    restart: always
    user: $UID:$GID
    ports:
      - "7080:7080"
    networks:
      - local-kafka
      - api-gateway
      - mongo-network
      - minio-network
      
  frontend:
    image: ghcr.io/reels-automation/reels-automation-frontend-new:main
    ports:
      - "80:80"
    restart: always
    environment:
      APP_API_URL: ${APP_API_URL}
    networks:
      - local-kafka

  prompt-generator:
    image: ghcr.io/reels-automation/reels-automation-prompt-generator:main
    networks:
      - local-kafka
      - ollama-docker
    environment:
      KAFKA_BROKER: ${KAFKA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_IP: ${OLLAMA_IP}
      KAFKA_BROKER_DOCKER: ${KAFKA_URL}
      OLLAMA_IP_DOCKER: ${OLLAMA_IP_DOCKER}
    stdin_open: true   
    tty: true
    restart: always    
    
  tts-rvc:
    image: ${TTS_RVC_IMAGE}
    environment:
      PYTHONUNBUFFERED: 1
      KAFKA_BROKER: ${KAFKA_URL}
      MINIO_ADDRESS: ${MINIO_PUBLIC_URL}
      MINIO_ACCESS_KEY: ${MINIO_PUBLIC_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PUBLIC_SECRET_KEY}
      ADMIN_API: ${ADMIN_API_NO_BACKSLASH}
    restart: always
    networks:
      - local-kafka
      - minio-network
      - minio-admin-files

  subtitle-generator:
    image: ghcr.io/reels-automation/reels-automation-subtitles-generator:main
    environment:
      PYTHONUNBUFFERED: 1
      KAFKA_BROKER: ${KAFKA_URL}
      KAFKA_BROKER_DOCKER: ${KAFKA_URL}
      MINIO_URL: ${MINIO_PUBLIC_URL}
      MINIO_URL_DOCKER: ${MINIO_PUBLIC_URL}
      MINIO_ACCESS_KEY: ${MINIO_PUBLIC_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PUBLIC_SECRET_KEY}
      ADMIN_API: ${ADMIN_API}
    restart: always
    networks:
      - local-kafka
      - minio-network
      - minio-admin-files
    volumes:
      - vosk-models:/app/voice_models
  
  video-creator:
      image: ghcr.io/reels-automation/reels-automation-video-creator:main
      networks:
        - local-kafka
        - minio-network
        - minio-admin-files
        - api-gateway
      environment:
        KAFKA_BROKER: ${KAFKA_URL}
        KAFKA_BROKER_DOCKER: ${KAFKA_URL}
        API_GATEWAY_URL: ${API_GATEWAY_URL}
        MINIO_URL: ${MINIO_PUBLIC_URL}
        SECURE: ${SECURE}
        ENVIRONMENT: ${ENVIRONMENT}
        ADMIN_API: ${ADMIN_API_NO_BACKSLASH}
        PUBLIC_MINIO_ACCESS_KEY: ${MINIO_PUBLIC_ACCESS_KEY}
        PUBLIC_MINIO_SECRET_KEY: ${MINIO_PUBLIC_SECRET_KEY}

      stdin_open: true   
      tty: true
      restart: always



networks:
  local-kafka:
    external: true
  ollama-docker:
    external: true
  minio-admin-files:
    external: true
  minio-network:
    external: true
  api-gateway:
    external: true
  mongo-network:
    external: true
      

volumes:
      vosk-models:
