services:
  api_gateway:
    image: ghcr.io/reels-automation/reels-automation-api-gateway-new:main
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      JWT_KEY: ${JWT_KEY}
      MINIO_URL: ${MINIO_URL}
      MONGO_URL: ${MONGO_URL}
      KAFKA_URL: ${KAFKA_URL}
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    container_name: api_gateway
    restart: unless-stopped
    user: $UID:$GID
    ports:
      - "7080:7080"
    networks:
      - local-kafka

  frontend:
    image: ghcr.io/reels-automation/reels-automation-frontend-new:main
    ports:
      - "80:80"
    environment:
      APP_API_URL: ${APP_API_URL}
    networks:
      - local-kafka

  prompt-generator:
    image: ghcr.io/reels-automation/reels-automation-prompt-generator:main
    networks:
      - local-kafka
      - ollama-docker
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_IP: ${OLLAMA_IP}
      KAFKA_BROKER_DOCKER: ${KAFKA_BROKER_DOCKER}
      OLLAMA_IP_DOCKER: ${OLLAMA_IP_DOCKER}
    stdin_open: true   
    tty: true          

networks:
  local-kafka:
    external: true
  ollama-docker:
    external: true